version: '3.0'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "8883:8883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      MQTT_SSL_ENABLED: true
      MQTT_SSL_CREDENTIALS_TYPE: PEM
      MQTT_SSL_PEM_CERT: /config/server.pem
      MQTT_SSL_PEM_KEY: /config/server_key.pem
    volumes:
      - ~/.mytb-config:/config
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
